name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Lint
        run: npm run lint

      - name: Notify
        run: |
          curl "https://api.telegram.org/bot7458007657:AAGSv4AjDmdhSE1079bJkCChBveSJqdKYTU/sendMessage?chat_id=-4582222854&text=HelloWorld"
