name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Lint
        run: npm run lint

      - name: Notify
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_SHA=$(git rev-parse HEAD)
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          MESSAGE="A new commit was merged to the repo:\n\nCommit: $COMMIT_MESSAGE\nSHA: $COMMIT_SHA\nAuthor: $COMMIT_AUTHOR"
          curl -X POST "https://api.telegram.org/bot7458007657:AAGSv4AjDmdhSE1079bJkCChBveSJqdKYTU/sendMessage" \
          -H "Content-Type: application/json" \
          -d "{\"chat_id\": \"-4582222854\", \"text\": \"$MESSAGE\"}"
